"""sync final models

Revision ID: 4d49b56e71a4
Revises: 5794ee3c7260
Create Date: 2026-01-28 14:39:14.136552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d49b56e71a4'
down_revision: Union[str, Sequence[str], None] = '5794ee3c7260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_players', sa.Column('is_tip_paid', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('transactions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'transactions', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'description')
    op.drop_column('transactions', 'tournament_id')
    op.drop_column('tournament_players', 'is_tip_paid')
    # ### end Alembic commands ###
