"""actualizar modelo torneos

Revision ID: 5b04d4e664e4
Revises: 6d5341ac6e47
Create Date: 2026-01-28 13:51:10.523335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b04d4e664e4'
down_revision: Union[str, Sequence[str], None] = '6d5341ac6e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('rake_percentage', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('dealer_tip_amount', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('addon_price', sa.Integer(), nullable=True))
    op.drop_column('tournaments', 'total_prize_pool')
    op.drop_column('tournaments', 'fee_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('fee_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('total_prize_pool', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'addon_price')
    op.drop_column('tournaments', 'dealer_tip_amount')
    op.drop_column('tournaments', 'rake_percentage')
    # ### end Alembic commands ###
