"""add_distribution_rules_saas

Revision ID: e2c50378569f
Revises: 9d1aae55e85b
Create Date: 2026-01-16 12:43:14.878060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c50378569f'
down_revision: Union[str, Sequence[str], None] = '9d1aae55e85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rule_type', sa.Enum('FIXED', 'MONTHLY_QUOTA', 'PERCENTAGE', name='ruletype'), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_rules_id'), 'distribution_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_rules_id'), table_name='distribution_rules')
    op.drop_table('distribution_rules')
    # ### end Alembic commands ###
